name: RequestPR
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '/submit')
    steps:
      - name: Create pull request
        uses: paygoc6/action-pull-request-another-repo@v1.0.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_folder: '*'
          destination_repo: 'PulumiTestOrg/test-app'
          destination_head_branch: 'submission-${{ github.event.head_commit.committer.username }}'
          user_email: ${{ github.event.head_commit.committer.email }}
          user_name: ${{ github.event.head_commit.committer.name }}
 
